local ADDON, MPH = ...
local L = MPH.L

L["window.title"]       = "MythicPresets Helper"
L["window.empty"]       = "No presets yet.\nPress |cffffd100New|r to create one."

L["button.new"]         = "New"
L["button.resetfilter"] = "Reset"
L["button.save"]        = "Save"
L["button.cancel"]      = "Cancel"
L["button.all"]         = "All"
L["button.none"]        = "None"

L["edit.titlenew"]      = "New preset"
L["edit.titleedit"]     = "Edit preset"
L["edit.name"]          = "Name"
L["edit.keylevel"]      = "Keystone level"
L["edit.keylevelhint"]  = "A reminder only - addons are not allowed to type into the Blizzard search box"
L["edit.dungeons"]      = "Dungeons"

L["kind.auto"]          = "auto"
L["kind.manual"]        = "manual"

L["tooltip.place"]      = "Reposition"
L["tooltip.placedesc"]  = "Works out the spot beside the group finder and pins the window there."
L["copy.ahead"]         = "Keys above"
L["copy.aheaddesc"]     = "How many levels above the preset to include in the search text. 0 searches the exact level."
L["copy.titleraid"]     = "Raid name"
L["copy.title"]         = "Keystone level"
L["copy.hint"]          = "Ctrl+C, then paste into the search box"
L["help.toggle"]        = "show or hide the preset window"
L["help.probe"]         = "group finder diagnostics"
L["help.offset"]        = "nudge the window further right"
L["help.reset"]         = "recompute the window position"

L["info.title"]         = "How to use"
L["info.step1"]         = "1. Click a preset. The dungeons are set for you."
L["info.step2"]         = "2. For a different keystone level a small box appears with the text ready. Copy it with Ctrl+C and paste it into the search box with Ctrl+V."
L["info.keep"]          = "To keep a preset, change it. Renaming is easiest. It then becomes manual and the addon stops updating it."
L["info.note"]          = "Only the level is typed by hand: Blizzard does not let addons write into the search box."

L["rating.label"]       = "Rating +/-"
L["rating.tooltip"]     = "Fills the M+ rating range in PGF around your own score when a preset is applied."
L["rating.current"]     = "Your score: %d. PGF will get %d - %d."
L["rating.noscore"]     = "Your score is not available yet."

L["summary.raid"]       = "from %d players, max %d in %s"
L["armor.plate"]        = "plate"
L["armor.mail"]         = "mail"
L["armor.leather"]      = "leather"
L["armor.cloth"]        = "cloth"
L["armor.unknown"]      = "your armor"
L["summary.nokey"]      = "any key"
L["summary.alldungeon"] = "all dungeons"
L["summary.dungeons"]   = "%d dungeons"

L["tooltip.auto"]       = "Built from your progress, refreshed automatically."
L["tooltip.manual"]     = "Created by hand, the addon leaves it alone."
L["tooltip.resetfilter"] = "Clears the applied preset and opens the search back up to every dungeon. No preset is deleted."
L["tooltip.apply"]      = "Click to apply this preset and search."
L["tooltip.edit"]       = "Edit"
L["tooltip.delete"]     = "Delete (hold Shift)"

L["msg.becamemanual"]   = "#%s is manual now"
L["msg.clearsearchbox"] = "Search box still has %s"
L["msg.notready"]       = "Not ready yet."
L["msg.positionreset"]  = "Position reset."
L["msg.raidnoedit"]     = "Raid presets are generated, not edited."
L["msg.needname"]       = "Name required."
L["msg.needdungeon"]    = "Pick at least one dungeon."
L["msg.nopanel"]        = "Open the group finder first."
L["msg.typekey"]        = "Type %s into the search box."
L["msg.pgfconflict"]    = "PGF also has dungeons checked - filters combine."
L["msg.nodungeondata"]  = "Data not loaded yet."
