if GetLocale() ~= "ruRU" then return end

local ADDON, MPH = ...
local L = MPH.L

L["window.title"]       = "MythicPresets Helper"
L["window.empty"]       = "Пресетов пока нет.\nНажмите |cffffd100Новый|r, чтобы создать."

L["button.new"]         = "Новый"
L["button.resetfilter"] = "Сброс"
L["button.save"]        = "Сохранить"
L["button.cancel"]      = "Отмена"
L["button.all"]         = "Все"
L["button.none"]        = "Ни одного"

L["edit.titlenew"]      = "Новый пресет"
L["edit.titleedit"]     = "Изменить пресет"
L["edit.name"]          = "Название"
L["edit.keylevel"]      = "Уровень ключа"
L["edit.keylevelhint"]  = "Только напоминание: вводить в строку поиска аддонам запрещено"
L["edit.dungeons"]      = "Подземелья"

L["kind.auto"]          = "авто"
L["kind.manual"]        = "ручной"

L["tooltip.place"]      = "Вернуть на место"
L["tooltip.placedesc"]  = "Вычисляет место рядом с поиском групп и закрепляет окно там."
L["copy.ahead"]         = "Ключей выше"
L["copy.aheaddesc"]     = "Сколько уровней сверх пресета попадёт в текст поиска. 0 ищет ровно этот уровень."
L["copy.titleraid"]     = "Название рейда"
L["copy.title"]         = "Уровень ключа"
L["copy.hint"]          = "Ctrl+C, затем вставьте в строку поиска"
L["help.toggle"]        = "показать или скрыть окно пресетов"
L["help.probe"]         = "диагностика поиска групп"
L["help.debug"]         = "включить или выключить пошаговый лог"
L["help.offset"]        = "сдвинуть окно правее"
L["help.reset"]         = "пересчитать положение окна"

L["info.title"]         = "Как пользоваться"
L["info.step1"]         = "1. Щёлкните пресет. Подземелья подставятся сами."
L["info.step2"]         = "2. Для другого уровня ключа появится окошко с готовым текстом. Скопируйте его через Ctrl+C и вставьте в строку поиска через Ctrl+V."
L["info.keep"]          = "Чтобы сохранить пресет, измените его. Проще всего переименовать. После этого он станет ручным и аддон больше не будет его обновлять."
L["info.note"]          = "Вручную вводится только уровень: Blizzard не разрешает аддонам писать в строку поиска."

L["rating.label"]       = "Рейтинг +/-"
L["rating.tooltip"]     = "При применении пресета подставляет в PGF диапазон M+ рейтинга вокруг вашего."
L["rating.current"]     = "Ваш рейтинг: %d. В PGF подставляет  %d - %d."
L["rating.noscore"]     = "Ваш рейтинг пока неизвестен."

L["summary.raid"]       = "от %d игроков, не больше %d в %s"
L["armor.plate"]        = "латах"
L["armor.mail"]         = "кольчуге"
L["armor.leather"]      = "коже"
L["armor.cloth"]        = "ткани"
L["armor.unknown"]      = "вашей броне"
L["summary.nokey"]      = "любой ключ"
L["summary.alldungeon"] = "все подземелья"
L["summary.dungeons"]   = "подземелий: %d"

L["tooltip.auto"]       = "Собран из прогресса, обновляется автоматически."
L["tooltip.manual"]     = "Создан вручную, аддон его не меняет."
L["tooltip.resetfilter"] = "Снимает применённый пресет и возвращает поиск ко всем подземельям. Ни один пресет не удаляется."
L["tooltip.apply"]      = "Щёлкните, чтобы применить пресет и выполнить поиск."
L["tooltip.edit"]       = "Изменить"
L["tooltip.delete"]     = "Удалить (с зажатым Shift)"

L["toggle.tooltip"]     = "Показать или скрыть окно пресетов."
L["toggle.pin"]         = "Правый клик возвращает окно на место рядом с поиском групп."

L["msg.becamemanual"]   = "#%s теперь ручной"
L["msg.clearsearchbox"] = "В строке поиска осталось %s"
L["msg.notready"]       = "Ещё не готово."
L["msg.positionreset"]  = "Положение сброшено."
L["msg.raidnoedit"]     = "Рейдовые пресеты генерируются, их не редактируют."
L["msg.needname"]       = "Нужно название."
L["msg.needdungeon"]    = "Отметьте хотя бы одно подземелье."
L["msg.nopanel"]        = "Сначала откройте поиск групп."
L["msg.typekey"]        = "Введите %s в строку поиска."
L["msg.pgfconflict"]    = "В PGF тоже отмечены подземелья — фильтры складываются."
L["msg.nodungeondata"]  = "Данные ещё не загружены."
